### ISSUE TITLE
Help With Wrong (and outdated) MYQ Garage door showing up in CarPlay dashboard (siri suggestion)

### ISSUE THREAD

**Issue by sebastiangoldstein** [iRayanKhan/homebridge-chamberlain#107]
# Explain the issue occurring:
Hi, I'm a Noob at HOOBS so I understand very little of what I am doing, that said:
I switched over to this Plugin because I was having configuration issues with some of the others.
This issue is not unique to this Plugin but maybe you can explain to me how to fix the problem.

I have two Garage doors hooked up to HomeKit via this plugin. In Car Play when I am close to my home a garage door shows up on the dashboard (Siri Suggestion) to allow me to open the door.
While for a while it was showing me the correct door (mine), now it shows me my wife's which I have no use as I want to get into my garage. I have no idea how to change this.

What's worse is that since I uninstalled the other MyQ plugin that I was testing and installed this one I re-added the garage doors and changed their names both in the Plug-In and Home Kit. However, the Siri Suggestion garage door is an older name, not even part of my Home Kit setup anymore. So not only does the wrong Garage door show up as a Siri suggestion but it is the wrong version of that door so it reports as "unresponsive."

# Expected Result
(Give a description of the expected behavior.)
I would love to be able to specify which garage door Siri suggestions displays on my CarPlay dashboard when I am close to my home. I have no idea if there is an Apple setting for this or a HOOBS plugin setting or an iPhone setting or a Carplay, however, since this is the most likely use case for MyQ in Homekit it would seem that it would be an issue that happens to many people with multiple garage doors. 

# Info
iOS Version: 13.6
Plugin Version: 1.6.1 published 6/25/2020 • 2 hours ago
HomeBridge Version: HOOBS 3.2.6
Node/Npm Version:

**Comment by iRayanKhan** [comment]
Hi, you're quite lucky to have a CarPlay dash I wish I had one lol.

So I notice that your problem is that the Siri Suggestions for the Garage Door at the bottom of the screen is supposed to show your garage door, rather than an old/other garage door. 

Unfortunately, this plugin doesn't touch CarPlay at all, it just adds it into HomeKit. Siri/On Device ML is what suggests what shows up, and no plugin can modify that. You could try resetting your CarPlay dash (if that's an option), or keep opening/closing your garage door, and have Siri learn it.

I hope this helps, or Apple lets you manually select a door in CarplayOS 14. 


Hope this helps, sorry I couldn't do much, but I hope it's a step in the right direction.

**Comment by iRayanKhan** [comment]
Closed: Native Apple Issue:

While it may have worked with the other plugin, switching plugins adds a new device, making Siri loose him/her knowledge on your device preference.
