### ISSUE TITLE
No response error

### ISSUE THREAD

**Issue by fillmoreracer** [iRayanKhan/homebridge-chamberlain#115]
# Explain the issue occuring:
Home app shows "No Response" on single garage door device. Just started happening 7/21, possible update on MyQ end. MyQ login credentials verified to work. MyQ stand-alone app works fine to control single device.

# Expected Result
Home app to communicate normally. 

# Info
iOS Version: 13.6
Plugin Version:1.6
HomeBridge Version:1.1.1
Node/Npm Version: 6.14.5

# Log Output:
![image](https://user-images.githubusercontent.com/68637809/88155513-c9a52900-cbcd-11ea-9def-c7d20e15cdab.png)

**Comment by iRayanKhan** [comment]
Hey there @fillmoreracer,

I ran into this issue last week too, and turns out my Pi's ethernet address wouldn't resolve DNS requests for some reason. 

I need some more info if you don't mind: 

Could you try to switch to Wi-Fi on your host machine? 

Do other plugins that require a server to connect to work?

**Comment by fillmoreracer** [comment]
My Pi is having connectivity issues. I believe this is the culprit.

**Comment by iRayanKhan** [comment]
@fillmoreracer glad to hear you found the issue, hope you can resolve it.

I don't know why ethernet just stopped, it's a 4B and is relatively new. Wi-Fi fixed it.

**Comment by fillmoreracer** [comment]
My Eero router was blocking its connection. Resetting everything resolved the issue. I believe there was a firmware update that caused it.
