### ISSUE TITLE
Light Swithes and Plugs

### ISSUE THREAD

**Issue by olds442** [iRayanKhan/homebridge-chamberlain#14]
Any thoughts of adding support for Liftmaster/Chamberlain RF lights and plugs as wells as the Garage doors?

The tool "sees" my Chamberlain Remote light switch and discovers its Device Id but it does not work and homebridge just generates errors

**Comment by caseywebdev** [comment]
Honestly I didn't even know that was a thing. I personally don't have plans on adding support as I run all of my plugs/switches through smartthings, but anyone is welcome to take a crack at it and open a PR.

**Comment by GaryREM** [comment]
The problem seems to be that it sees the light device and may not know what to do with it. 

Right now I am getting an error "Error: Multiple controllable devices found:" and if I add the accessory and restart, I am still getting the message.

I see that 3 accessories are identified and loaded and they show up in the Home app, but the error still occurs.

**Comment by andrewfawcett** [comment]
Strange, I only have a Garage Door Opener but I see two devices as well. Is the remote light switch on the wall unit that also opens/ closes the garage door?

**Comment by bogdanbun** [comment]
I believe the other device is the light switch. Would be great to add this one as another accessory/switch.

**Comment by iRayanKhan** [comment]
Closed;
Inactive.
May revisit later as I also have lights on my garage opener and saw an issue asking about door locks.
