### ISSUE TITLE
is this the http issue?

### ISSUE THREAD

**Issue by t0lbert64** [iRayanKhan/homebridge-chamberlain#70]
did chamberlain mess with their API?

here is a screenshot of the error.  was workin perfect, than just started doing this like 2-3 weeks ago i believe?

thank you.
<img width="737" alt="Screen Shot 2019-11-01 at 7 34 36 PM" src="https://user-images.githubusercontent.com/49455193/68064895-0dbe6980-fcdf-11e9-88ea-e6649d2a8a49.png">

**Comment by iRayanKhan** [comment]
Hello @t0lbert64 , this issue was resolved in the past few releases. To fix this do the following
1) Update the plugin
2) In the ```config.json``` file remove the ```"deviceID"``` parameter 
3) Run HomeBridge with the ```deviceID``` parameter empty
4) Plugin will crash and spit a __new__ ```deviceID```
5) Enter in the ```deviceID``` that starts with ```CG``` in your ```config.json``` file.
This should fix it, let me know if you need any assistance!

**Comment by t0lbert64** [comment]
yup. nailed it.  just did that and was going to erase my issue.  thanks for the quick reply.
